// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IDemoInterface.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AutogenerateProto.Interfaces {

  /// <summary>Holder for reflection information generated from IDemoInterface.proto</summary>
  public static partial class IDemoInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for IDemoInterface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IDemoInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRJRGVtb0ludGVyZmFjZS5wcm90bxIdYXV0b2dlbmVyYXRlX3Byb3RvLklu",
            "dGVyZmFjZXMaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aFnBy",
            "b3RvYnVmLW5ldC9iY2wucHJvdG8i4QEKDERlbW9Db250cmFjdBIQCghJZFZh",
            "bHVlMRgBIAEoCRIQCghJZFZhbHVlMhgCIAEoCRIRCglJbnRWYWx1ZTEYAyAB",
            "KAUSEQoJSW50VmFsdWUyGAQgASgFEhMKC0Zsb2F0VmFsdWUxGAUgASgCEhMK",
            "C0Zsb2F0VmFsdWUyGAYgASgCEhQKDFN0cmluZ1ZhbHVlMRgHIAEoCRIUCgxT",
            "dHJpbmdWYWx1ZTIYCCABKAkSGAoBYRgJIAEoCzINLmJjbC5EYXRlVGltZRIX",
            "CgR1dWlkGAogASgLMgkuYmNsLkd1aWQigwEKDURlbW9Db250cmFjdDISDwoH",
            "SWRWYWx1ZRgBIAEoCRIuCgp0aW1lc3RhbXBzGAIgASgLMhouZ29vZ2xlLnBy",
            "b3RvYnVmLlRpbWVzdGFtcBIYCgFhGAMgASgLMg0uYmNsLkRhdGVUaW1lEhcK",
            "BHV1aWQYBCABKAsyCS5iY2wuR3VpZDJ9Cg1EZW1vSW50ZXJmYWNlEmwKD0dl",
            "dERlbW9Db250cmFjdBIsLmF1dG9nZW5lcmF0ZV9wcm90by5JbnRlcmZhY2Vz",
            "LkRlbW9Db250cmFjdDIaKy5hdXRvZ2VuZXJhdGVfcHJvdG8uSW50ZXJmYWNl",
            "cy5EZW1vQ29udHJhY3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::ProtoBuf.Bcl.BclReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AutogenerateProto.Interfaces.DemoContract), global::AutogenerateProto.Interfaces.DemoContract.Parser, new[]{ "IdValue1", "IdValue2", "IntValue1", "IntValue2", "FloatValue1", "FloatValue2", "StringValue1", "StringValue2", "A", "Uuid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AutogenerateProto.Interfaces.DemoContract2), global::AutogenerateProto.Interfaces.DemoContract2.Parser, new[]{ "IdValue", "Timestamps", "A", "Uuid" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DemoContract : pb::IMessage<DemoContract> {
    private static readonly pb::MessageParser<DemoContract> _parser = new pb::MessageParser<DemoContract>(() => new DemoContract());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DemoContract> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AutogenerateProto.Interfaces.IDemoInterfaceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract(DemoContract other) : this() {
      idValue1_ = other.idValue1_;
      idValue2_ = other.idValue2_;
      intValue1_ = other.intValue1_;
      intValue2_ = other.intValue2_;
      floatValue1_ = other.floatValue1_;
      floatValue2_ = other.floatValue2_;
      stringValue1_ = other.stringValue1_;
      stringValue2_ = other.stringValue2_;
      a_ = other.a_ != null ? other.a_.Clone() : null;
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract Clone() {
      return new DemoContract(this);
    }

    /// <summary>Field number for the "IdValue1" field.</summary>
    public const int IdValue1FieldNumber = 1;
    private string idValue1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdValue1 {
      get { return idValue1_; }
      set {
        idValue1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IdValue2" field.</summary>
    public const int IdValue2FieldNumber = 2;
    private string idValue2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdValue2 {
      get { return idValue2_; }
      set {
        idValue2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IntValue1" field.</summary>
    public const int IntValue1FieldNumber = 3;
    private int intValue1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IntValue1 {
      get { return intValue1_; }
      set {
        intValue1_ = value;
      }
    }

    /// <summary>Field number for the "IntValue2" field.</summary>
    public const int IntValue2FieldNumber = 4;
    private int intValue2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IntValue2 {
      get { return intValue2_; }
      set {
        intValue2_ = value;
      }
    }

    /// <summary>Field number for the "FloatValue1" field.</summary>
    public const int FloatValue1FieldNumber = 5;
    private float floatValue1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float FloatValue1 {
      get { return floatValue1_; }
      set {
        floatValue1_ = value;
      }
    }

    /// <summary>Field number for the "FloatValue2" field.</summary>
    public const int FloatValue2FieldNumber = 6;
    private float floatValue2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float FloatValue2 {
      get { return floatValue2_; }
      set {
        floatValue2_ = value;
      }
    }

    /// <summary>Field number for the "StringValue1" field.</summary>
    public const int StringValue1FieldNumber = 7;
    private string stringValue1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue1 {
      get { return stringValue1_; }
      set {
        stringValue1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "StringValue2" field.</summary>
    public const int StringValue2FieldNumber = 8;
    private string stringValue2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue2 {
      get { return stringValue2_; }
      set {
        stringValue2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 9;
    private global::ProtoBuf.Bcl.DateTime a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBuf.Bcl.DateTime A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 10;
    private global::ProtoBuf.Bcl.Guid uuid_;
    /// <summary>
    /// default value could not be applied: 00000000-0000-0000-0000-000000000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBuf.Bcl.Guid Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DemoContract);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DemoContract other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdValue1 != other.IdValue1) return false;
      if (IdValue2 != other.IdValue2) return false;
      if (IntValue1 != other.IntValue1) return false;
      if (IntValue2 != other.IntValue2) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue1, other.FloatValue1)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue2, other.FloatValue2)) return false;
      if (StringValue1 != other.StringValue1) return false;
      if (StringValue2 != other.StringValue2) return false;
      if (!object.Equals(A, other.A)) return false;
      if (!object.Equals(Uuid, other.Uuid)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdValue1.Length != 0) hash ^= IdValue1.GetHashCode();
      if (IdValue2.Length != 0) hash ^= IdValue2.GetHashCode();
      if (IntValue1 != 0) hash ^= IntValue1.GetHashCode();
      if (IntValue2 != 0) hash ^= IntValue2.GetHashCode();
      if (FloatValue1 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue1);
      if (FloatValue2 != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue2);
      if (StringValue1.Length != 0) hash ^= StringValue1.GetHashCode();
      if (StringValue2.Length != 0) hash ^= StringValue2.GetHashCode();
      if (a_ != null) hash ^= A.GetHashCode();
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdValue1.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdValue1);
      }
      if (IdValue2.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdValue2);
      }
      if (IntValue1 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IntValue1);
      }
      if (IntValue2 != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(IntValue2);
      }
      if (FloatValue1 != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(FloatValue1);
      }
      if (FloatValue2 != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(FloatValue2);
      }
      if (StringValue1.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StringValue1);
      }
      if (StringValue2.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StringValue2);
      }
      if (a_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(A);
      }
      if (uuid_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdValue1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdValue1);
      }
      if (IdValue2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdValue2);
      }
      if (IntValue1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntValue1);
      }
      if (IntValue2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntValue2);
      }
      if (FloatValue1 != 0F) {
        size += 1 + 4;
      }
      if (FloatValue2 != 0F) {
        size += 1 + 4;
      }
      if (StringValue1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue1);
      }
      if (StringValue2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue2);
      }
      if (a_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(A);
      }
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DemoContract other) {
      if (other == null) {
        return;
      }
      if (other.IdValue1.Length != 0) {
        IdValue1 = other.IdValue1;
      }
      if (other.IdValue2.Length != 0) {
        IdValue2 = other.IdValue2;
      }
      if (other.IntValue1 != 0) {
        IntValue1 = other.IntValue1;
      }
      if (other.IntValue2 != 0) {
        IntValue2 = other.IntValue2;
      }
      if (other.FloatValue1 != 0F) {
        FloatValue1 = other.FloatValue1;
      }
      if (other.FloatValue2 != 0F) {
        FloatValue2 = other.FloatValue2;
      }
      if (other.StringValue1.Length != 0) {
        StringValue1 = other.StringValue1;
      }
      if (other.StringValue2.Length != 0) {
        StringValue2 = other.StringValue2;
      }
      if (other.a_ != null) {
        if (a_ == null) {
          A = new global::ProtoBuf.Bcl.DateTime();
        }
        A.MergeFrom(other.A);
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::ProtoBuf.Bcl.Guid();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdValue1 = input.ReadString();
            break;
          }
          case 18: {
            IdValue2 = input.ReadString();
            break;
          }
          case 24: {
            IntValue1 = input.ReadInt32();
            break;
          }
          case 32: {
            IntValue2 = input.ReadInt32();
            break;
          }
          case 45: {
            FloatValue1 = input.ReadFloat();
            break;
          }
          case 53: {
            FloatValue2 = input.ReadFloat();
            break;
          }
          case 58: {
            StringValue1 = input.ReadString();
            break;
          }
          case 66: {
            StringValue2 = input.ReadString();
            break;
          }
          case 74: {
            if (a_ == null) {
              A = new global::ProtoBuf.Bcl.DateTime();
            }
            input.ReadMessage(A);
            break;
          }
          case 82: {
            if (uuid_ == null) {
              Uuid = new global::ProtoBuf.Bcl.Guid();
            }
            input.ReadMessage(Uuid);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DemoContract2 : pb::IMessage<DemoContract2> {
    private static readonly pb::MessageParser<DemoContract2> _parser = new pb::MessageParser<DemoContract2>(() => new DemoContract2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DemoContract2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AutogenerateProto.Interfaces.IDemoInterfaceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract2(DemoContract2 other) : this() {
      idValue_ = other.idValue_;
      timestamps_ = other.timestamps_ != null ? other.timestamps_.Clone() : null;
      a_ = other.a_ != null ? other.a_.Clone() : null;
      uuid_ = other.uuid_ != null ? other.uuid_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoContract2 Clone() {
      return new DemoContract2(this);
    }

    /// <summary>Field number for the "IdValue" field.</summary>
    public const int IdValueFieldNumber = 1;
    private string idValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdValue {
      get { return idValue_; }
      set {
        idValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamps" field.</summary>
    public const int TimestampsFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamps {
      get { return timestamps_; }
      set {
        timestamps_ = value;
      }
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 3;
    private global::ProtoBuf.Bcl.DateTime a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBuf.Bcl.DateTime A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 4;
    private global::ProtoBuf.Bcl.Guid uuid_;
    /// <summary>
    /// default value could not be applied: 00000000-0000-0000-0000-000000000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtoBuf.Bcl.Guid Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DemoContract2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DemoContract2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdValue != other.IdValue) return false;
      if (!object.Equals(Timestamps, other.Timestamps)) return false;
      if (!object.Equals(A, other.A)) return false;
      if (!object.Equals(Uuid, other.Uuid)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdValue.Length != 0) hash ^= IdValue.GetHashCode();
      if (timestamps_ != null) hash ^= Timestamps.GetHashCode();
      if (a_ != null) hash ^= A.GetHashCode();
      if (uuid_ != null) hash ^= Uuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdValue.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdValue);
      }
      if (timestamps_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamps);
      }
      if (a_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(A);
      }
      if (uuid_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdValue);
      }
      if (timestamps_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamps);
      }
      if (a_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(A);
      }
      if (uuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DemoContract2 other) {
      if (other == null) {
        return;
      }
      if (other.IdValue.Length != 0) {
        IdValue = other.IdValue;
      }
      if (other.timestamps_ != null) {
        if (timestamps_ == null) {
          Timestamps = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamps.MergeFrom(other.Timestamps);
      }
      if (other.a_ != null) {
        if (a_ == null) {
          A = new global::ProtoBuf.Bcl.DateTime();
        }
        A.MergeFrom(other.A);
      }
      if (other.uuid_ != null) {
        if (uuid_ == null) {
          Uuid = new global::ProtoBuf.Bcl.Guid();
        }
        Uuid.MergeFrom(other.Uuid);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdValue = input.ReadString();
            break;
          }
          case 18: {
            if (timestamps_ == null) {
              Timestamps = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamps);
            break;
          }
          case 26: {
            if (a_ == null) {
              A = new global::ProtoBuf.Bcl.DateTime();
            }
            input.ReadMessage(A);
            break;
          }
          case 34: {
            if (uuid_ == null) {
              Uuid = new global::ProtoBuf.Bcl.Guid();
            }
            input.ReadMessage(Uuid);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
